console.log("=======Step 1=======");
var sweety="Sweety";
var cutie="Cutie";
console.log("Before Swapping");
console.log("I am Sweety-->",sweety);
console.log("I am Cutie-->",cutie);
var name=sweety;
sweety=cutie;
cutie=name;
console.log("After Swapping");
console.log("I am Sweety-->",sweety);
console.log("I am Cutie-->",cutie);
console.log("=======Step 2=======");
var num1="100";
var num2="200";
var num3="300";
console.log("Before Swapping");
console.log("Number1-->",num1);
console.log("Number2-->",num2);
console.log("Number3-->",num3);
var temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("After Swapping");
console.log("Number1-->",num1);
console.log("Number2-->",num2);
console.log("Number3-->",num3);